# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_ups.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x61mazon_ups.proto\"/\n\x0cUSendWorldId\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"\x1b\n\x0b\x41GotWorldId\x12\x0c\n\x04\x61\x63ks\x18\x01 \x02(\x03\"9\n\x07Product\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"\x85\x01\n\x0e\x41RequirePickup\x12\x12\n\nupsaccount\x18\x01 \x02(\t\x12\r\n\x05whnum\x18\x02 \x02(\x05\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\x0e\n\x06shipid\x18\x05 \x02(\x03\x12\x1a\n\x08products\x18\x06 \x03(\x0b\x32\x08.Product\x12\x0e\n\x06seqnum\x18\x07 \x02(\x03\"W\n\x0fUPickupReceived\x12\x0e\n\x06shipid\x18\x01 \x02(\x03\x12\x13\n\x0btrackingnum\x18\x02 \x02(\t\x12\x0f\n\x07truckid\x18\x03 \x02(\x03\x12\x0e\n\x06seqnum\x18\x04 \x02(\x03\"T\n\x0b\x41PackLoaded\x12\x0e\n\x06shipid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\t\n\x01x\x18\x03 \x02(\x05\x12\t\n\x01y\x18\x04 \x02(\x05\x12\x0e\n\x06seqnum\x18\x05 \x02(\x03\"-\n\x0bUPackLoaded\x12\x0e\n\x06shipid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"0\n\x0eUPackDelivered\x12\x0e\n\x06shipid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"8\n\x03\x45rr\x12\x0b\n\x03\x65rr\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"v\n\x08\x41Message\x12\"\n\treqPickup\x18\x01 \x03(\x0b\x32\x0f.ARequirePickup\x12#\n\rreqPackLoaded\x18\x02 \x03(\x0b\x32\x0c.APackLoaded\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\x12\x13\n\x05\x65rror\x18\x04 \x03(\x0b\x32\x04.Err\"\xa7\x01\n\x08UMessage\x12(\n\x0epickupReceived\x18\x01 \x03(\x0b\x32\x10.UPickupReceived\x12#\n\rresPackLoaded\x18\x02 \x03(\x0b\x32\x0c.UPackLoaded\x12)\n\x10reqPackDelivered\x18\x03 \x03(\x0b\x32\x0f.UPackDelivered\x12\x0c\n\x04\x61\x63ks\x18\x04 \x03(\x03\x12\x13\n\x05\x65rror\x18\x05 \x03(\x0b\x32\x04.Err')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USENDWORLDID = _descriptor.Descriptor(
  name='USendWorldId',
  full_name='USendWorldId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='USendWorldId.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='USendWorldId.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=67,
)


_AGOTWORLDID = _descriptor.Descriptor(
  name='AGotWorldId',
  full_name='AGotWorldId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acks', full_name='AGotWorldId.acks', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=96,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Product.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Product.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Product.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=155,
)


_AREQUIREPICKUP = _descriptor.Descriptor(
  name='ARequirePickup',
  full_name='ARequirePickup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upsaccount', full_name='ARequirePickup.upsaccount', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='ARequirePickup.whnum', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='ARequirePickup.x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='ARequirePickup.y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shipid', full_name='ARequirePickup.shipid', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='products', full_name='ARequirePickup.products', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='ARequirePickup.seqnum', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=291,
)


_UPICKUPRECEIVED = _descriptor.Descriptor(
  name='UPickupReceived',
  full_name='UPickupReceived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UPickupReceived.shipid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackingnum', full_name='UPickupReceived.trackingnum', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UPickupReceived.truckid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UPickupReceived.seqnum', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=380,
)


_APACKLOADED = _descriptor.Descriptor(
  name='APackLoaded',
  full_name='APackLoaded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipid', full_name='APackLoaded.shipid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='APackLoaded.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='APackLoaded.x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='APackLoaded.y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='APackLoaded.seqnum', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=466,
)


_UPACKLOADED = _descriptor.Descriptor(
  name='UPackLoaded',
  full_name='UPackLoaded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UPackLoaded.shipid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UPackLoaded.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=513,
)


_UPACKDELIVERED = _descriptor.Descriptor(
  name='UPackDelivered',
  full_name='UPackDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UPackDelivered.shipid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UPackDelivered.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=563,
)


_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='Err.err', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originseqnum', full_name='Err.originseqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Err.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=621,
)


_AMESSAGE = _descriptor.Descriptor(
  name='AMessage',
  full_name='AMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqPickup', full_name='AMessage.reqPickup', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqPackLoaded', full_name='AMessage.reqPackLoaded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acks', full_name='AMessage.acks', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='AMessage.error', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=741,
)


_UMESSAGE = _descriptor.Descriptor(
  name='UMessage',
  full_name='UMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickupReceived', full_name='UMessage.pickupReceived', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resPackLoaded', full_name='UMessage.resPackLoaded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqPackDelivered', full_name='UMessage.reqPackDelivered', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UMessage.acks', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='UMessage.error', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=744,
  serialized_end=911,
)

_AREQUIREPICKUP.fields_by_name['products'].message_type = _PRODUCT
_AMESSAGE.fields_by_name['reqPickup'].message_type = _AREQUIREPICKUP
_AMESSAGE.fields_by_name['reqPackLoaded'].message_type = _APACKLOADED
_AMESSAGE.fields_by_name['error'].message_type = _ERR
_UMESSAGE.fields_by_name['pickupReceived'].message_type = _UPICKUPRECEIVED
_UMESSAGE.fields_by_name['resPackLoaded'].message_type = _UPACKLOADED
_UMESSAGE.fields_by_name['reqPackDelivered'].message_type = _UPACKDELIVERED
_UMESSAGE.fields_by_name['error'].message_type = _ERR
DESCRIPTOR.message_types_by_name['USendWorldId'] = _USENDWORLDID
DESCRIPTOR.message_types_by_name['AGotWorldId'] = _AGOTWORLDID
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['ARequirePickup'] = _AREQUIREPICKUP
DESCRIPTOR.message_types_by_name['UPickupReceived'] = _UPICKUPRECEIVED
DESCRIPTOR.message_types_by_name['APackLoaded'] = _APACKLOADED
DESCRIPTOR.message_types_by_name['UPackLoaded'] = _UPACKLOADED
DESCRIPTOR.message_types_by_name['UPackDelivered'] = _UPACKDELIVERED
DESCRIPTOR.message_types_by_name['Err'] = _ERR
DESCRIPTOR.message_types_by_name['AMessage'] = _AMESSAGE
DESCRIPTOR.message_types_by_name['UMessage'] = _UMESSAGE

USendWorldId = _reflection.GeneratedProtocolMessageType('USendWorldId', (_message.Message,), dict(
  DESCRIPTOR = _USENDWORLDID,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:USendWorldId)
  ))
_sym_db.RegisterMessage(USendWorldId)

AGotWorldId = _reflection.GeneratedProtocolMessageType('AGotWorldId', (_message.Message,), dict(
  DESCRIPTOR = _AGOTWORLDID,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AGotWorldId)
  ))
_sym_db.RegisterMessage(AGotWorldId)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  ))
_sym_db.RegisterMessage(Product)

ARequirePickup = _reflection.GeneratedProtocolMessageType('ARequirePickup', (_message.Message,), dict(
  DESCRIPTOR = _AREQUIREPICKUP,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ARequirePickup)
  ))
_sym_db.RegisterMessage(ARequirePickup)

UPickupReceived = _reflection.GeneratedProtocolMessageType('UPickupReceived', (_message.Message,), dict(
  DESCRIPTOR = _UPICKUPRECEIVED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UPickupReceived)
  ))
_sym_db.RegisterMessage(UPickupReceived)

APackLoaded = _reflection.GeneratedProtocolMessageType('APackLoaded', (_message.Message,), dict(
  DESCRIPTOR = _APACKLOADED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:APackLoaded)
  ))
_sym_db.RegisterMessage(APackLoaded)

UPackLoaded = _reflection.GeneratedProtocolMessageType('UPackLoaded', (_message.Message,), dict(
  DESCRIPTOR = _UPACKLOADED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UPackLoaded)
  ))
_sym_db.RegisterMessage(UPackLoaded)

UPackDelivered = _reflection.GeneratedProtocolMessageType('UPackDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UPACKDELIVERED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UPackDelivered)
  ))
_sym_db.RegisterMessage(UPackDelivered)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), dict(
  DESCRIPTOR = _ERR,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  ))
_sym_db.RegisterMessage(Err)

AMessage = _reflection.GeneratedProtocolMessageType('AMessage', (_message.Message,), dict(
  DESCRIPTOR = _AMESSAGE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AMessage)
  ))
_sym_db.RegisterMessage(AMessage)

UMessage = _reflection.GeneratedProtocolMessageType('UMessage', (_message.Message,), dict(
  DESCRIPTOR = _UMESSAGE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UMessage)
  ))
_sym_db.RegisterMessage(UMessage)


# @@protoc_insertion_point(module_scope)
