# Generated by Django 3.1.7 on 2021-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('owner', models.CharField(max_length=30, null=True)),
                ('package_status', models.CharField(choices=[('created', 'created'), ('in the warehouse', 'in the warehouse'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='created', max_length=30)),
                ('dest_x', models.IntegerField(null=True)),
                ('dest_y', models.IntegerField(null=True)),
                ('truck_id', models.IntegerField(null=True)),
            ],
        ),
    ]
