# Generated by Django 3.1.7 on 2021-04-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='owner',
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_set', to='ups.user'),
        ),
    ]
