# Generated by Django 3.1.7 on 2021-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0004_auto_20210417_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='product',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_status',
        ),
        migrations.AddField(
            model_name='package',
            name='tracking_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='wh_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='wh_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='wh_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
