# Generated by Django 3.1.7 on 2021-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0005_auto_20210417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_num',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
