# Generated by Django 3.1.7 on 2021-04-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0007_product_product_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_package',
            new_name='productPackage',
        ),
    ]
