# Generated by Django 3.1.7 on 2021-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0008_auto_20210417_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productPackage',
            new_name='product_package',
        ),
    ]
