# Generated by Django 3.1.5 on 2021-04-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0009_auto_20210417_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.TextField(default='idle'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truck',
            name='x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='y',
            field=models.IntegerField(default=1),
        ),
    ]
